"""change_some_fields

Revision ID: 2952d0495035
Revises: 95fdb3ed3a6a
Create Date: 2024-06-10 09:55:34.643892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2952d0495035"
down_revision: Union[str, None] = "95fdb3ed3a6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movies", "directors", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("movies", "cast", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movies", "cast", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("movies", "directors", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
