"""db_initial

Revision ID: 95fdb3ed3a6a
Revises:
Create Date: 2024-06-10 09:49:18.572704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95fdb3ed3a6a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("release_date", sa.String(), nullable=False),
        sa.Column("duration", sa.String(), nullable=True),
        sa.Column("kinds", sa.String(), nullable=False),
        sa.Column("directors", sa.String(), nullable=False),
        sa.Column("cast", sa.String(), nullable=False),
        sa.Column("original_title", sa.String(), nullable=True),
        sa.Column("note", sa.Float(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("pk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pk_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies")
    # ### end Alembic commands ###
